# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.3.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, : -1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [5]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

## Part 2 - Building the ANN

### Initializing the ANN

In [7]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [8]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [9]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [10]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [11]:
ann.compile(optimizer='adam', loss='mean_squared_error')

### Training the ANN model on the Training set

In [12]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
240/240 [==============================] - 0s 889us/step - loss: 94757.3672
Epoch 2/100
240/240 [==============================] - 0s 948us/step - loss: 591.5391
Epoch 3/100
240/240 [==============================] - 0s 947us/step - loss: 480.7013
Epoch 4/100
240/240 [==============================] - 0s 888us/step - loss: 466.2551
Epoch 5/100
240/240 [==============================] - 0s 882us/step - loss: 448.3560
Epoch 6/100
240/240 [==============================] - 0s 871us/step - loss: 428.5102
Epoch 7/100
240/240 [==============================] - 0s 946us/step - loss: 406.5360
Epoch 8/100
240/240 [==============================] - 0s 902us/step - loss: 382.7055
Epoch 9/100
240/240 [==============================] - 0s 867us/step - loss: 357.3058
Epoch 10/100
240/240 [==============================] - 0s 835us/step - loss: 330.5050
Epoch 11/100
240/240 [==============================] - 0s 876us/step - loss: 303.1794
Epoch 12/100
240/240 [============================

### Predicting the results of the Test set

In [15]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[432.06 431.23]
 [463.35 460.01]
 [466.92 461.14]
 ...
 [474.03 473.26]
 [441.04 438.  ]
 [460.18 463.28]]
